apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
spec:
  selector:
    matchLabels:
      app: ldap
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
        role: master
        tier: backend
    spec:
      containers:
      - name: ldap
        image: ldapaccountmanager/lam
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
          - name: LAM_SKIP_PRECONFIGURE
            value: "true"
