apiVersion: v1
kind: Pod
metadata:
  name: ldap
spec:
  containers:
    - name: ldap-container
      image: boxy14/public:v1
      command: [ "/bin/sh"]
      args: ["-c","sleep 600"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"

      ports:
      - containerPort: 389

      env:
      - name: admin
        value: "admin"
      - name: password
        value: "test1234"

  restartPolicy: Never
