apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
spec:
  selector:
    matchLabels:
      app: ldap
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
        role: master
        tier: backend
    spec:
      containers:
      - name: ldap
        image: boxy14/public:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 369
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-service
spec:
  type: NodePort
  selector:
    app: ldap
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 369
      targetPort: 369
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30207
