apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  selector:
    matchLabels:
      app: openldap
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
        role: master
        tier: backend
    spec:
      containers:
      - name: openldap
        image: mwaeckerlin/openldap
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 389
        env:
          - name: DOMAIN
            value: "my-company.com"
          - name: ORGANIZATION
            value: "My Company"
          - name: PASSWORD
            value: "12345678"
          - name: DEBUG_LEVEL
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
spec:
  type: NodePort
  selector:
    app: openldap
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 389
      targetPort: 389
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30055

