---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    app: nginx
spec: 
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["/bin/sh"]
    args: ["-c","sleep 600"]

    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/


