apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: user-mohamed 
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - name: redis
      nodePort: 32701
      port: 6379
      protocol: TCP
