---
apiVersion: v1
kind: Pod
metadata: 
  name: redis
  labels:
    app: redis
spec: 
  volumes:
  - name: redis-config
    configMap:
      name: redis-demo-config
      items:
        - key: redis.conf
          path: redis.conf
  replicas: 1
  selector:
    matchLabels:
      app: redis
  containers:
  - name: redis
    image: redis:latest
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["/bin/sh"]
    args: ["-c","sleep 600"]

    volumeMounts:
    - name: redis-config
    mountPath: /redis.conf

    Ports:
    - containerPort: 6479


